# Generated by Django 4.0.3 on 2022-03-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_remove_question_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='xd', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(default='xd', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(default='xd', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(default='xd', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(default='xd', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='xd', max_length=200),
            preserve_default=False,
        ),
    ]
