# Generated by Django 4.0.3 on 2022-03-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0009_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
