# Generated by Django 4.0.3 on 2022-03-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0011_question_category_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Music', 'Music'), ('Science', 'Science'), ('Literature', 'Literature'), ('Movies', 'Movies')], default='Other', max_length=200),
        ),
    ]
